export const generateEmailTemplate = (
        name: string,
        email: string,
        companyName: string,
        message: string
      ): string => {
        return `
          <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 30px; border: 1px solid #eaeaea; border-radius: 10px; background-color: #ffffff; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
            <h2 style="color: #003366; font-size: 26px; border-bottom: 2px solid #eaeaea; padding-bottom: 10px; margin-bottom: 20px;">New Contact Us Message</h2>
            
            <p style="font-size: 18px; line-height: 1.6; color: #333333;">
              You have received a new message from <strong style="color: #003366;">${name}</strong> (<a href="mailto:${email}" style="color: #003366; text-decoration: none;">${email}</a>).
            </p>
            
            <div style="background-color: #f9f9f9; padding: 20px; margin: 20px 0; border-radius: 8px; border-left: 4px solid #003366;">
              <p style="font-size: 16px; line-height: 1.5; color: #333333; margin: 0;">"${message}"</p>
            </div>
      
            <p style="font-size: 16px; color: #666666;">
              For further assistance, please reply to this email or contact <strong>${name}</strong> directly at 
              <a href="mailto:${email}" style="color: #003366; text-decoration: none; font-weight: bold;">${email}</a>.
            </p>
      
            <p style="font-size: 14px; color: #999999;">
              This email was generated by the Contact Us form on your website.
            </p>
            
            <footer style="text-align: center; padding: 15px 0; border-top: 2px solid #eaeaea; margin-top: 30px; font-size: 12px; color: #999999;">
              &copy; ${new Date().getFullYear()} ${companyName}. All rights reserved.
            </footer>
          </div>
        `;
      };
      